project:
  type: website
  output-dir: docs

website:
  title: "tutorial_sitio_web_quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/bastianolea
      - icon: linkedin
        href: https://www.linkedin.com/in/bastianolea/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

